onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /lcd_top_tb/clk_tb
add wave -noupdate /lcd_top_tb/rst_n_tb
add wave -noupdate /lcd_top_tb/AS_Address_tb
add wave -noupdate /lcd_top_tb/AS_ChipSelect_tb
add wave -noupdate /lcd_top_tb/AS_Wr_tb
add wave -noupdate /lcd_top_tb/AS_WrData_tb
add wave -noupdate /lcd_top_tb/AS_Rd_tb
add wave -noupdate /lcd_top_tb/AS_RdData_tb
add wave -noupdate /lcd_top_tb/AS_IRQ_tb
add wave -noupdate /lcd_top_tb/AS_WaitRequest_tb
add wave -noupdate /lcd_top_tb/AM_Address_tb
add wave -noupdate /lcd_top_tb/AM_ByteEnable_tb
add wave -noupdate /lcd_top_tb/AM_Rd_tb
add wave -noupdate /lcd_top_tb/AM_RdDataValid_tb
add wave -noupdate /lcd_top_tb/AM_Burstcount_tb
add wave -noupdate /lcd_top_tb/AM_RdData_tb
add wave -noupdate /lcd_top_tb/AM_WaitRequest_tb
add wave -noupdate /lcd_top_tb/CS_n_tb
add wave -noupdate /lcd_top_tb/DC_n_tb
add wave -noupdate /lcd_top_tb/Wr_n_tb
add wave -noupdate /lcd_top_tb/Rd_n_tb
add wave -noupdate /lcd_top_tb/D_tb
add wave -noupdate /lcd_top_tb/phase_id
add wave -noupdate /lcd_top_tb/done
add wave -noupdate /lcd_top_tb/DUV/CTRL/clk
add wave -noupdate /lcd_top_tb/DUV/CTRL/rst_n
add wave -noupdate /lcd_top_tb/DUV/CTRL/CS_n
add wave -noupdate /lcd_top_tb/DUV/CTRL/DC_n
add wave -noupdate /lcd_top_tb/DUV/CTRL/Wr_n
add wave -noupdate /lcd_top_tb/DUV/CTRL/Rd_n
add wave -noupdate /lcd_top_tb/DUV/CTRL/D
add wave -noupdate /lcd_top_tb/DUV/CTRL/LCD_ON
add wave -noupdate /lcd_top_tb/DUV/CTRL/RESET_N
add wave -noupdate /lcd_top_tb/DUV/CTRL/LS_DC_n
add wave -noupdate /lcd_top_tb/DUV/CTRL/LS_Wr_n
add wave -noupdate /lcd_top_tb/DUV/CTRL/LS_WrData
add wave -noupdate /lcd_top_tb/DUV/CTRL/LS_RdData
add wave -noupdate /lcd_top_tb/DUV/CTRL/LS_Rd_n
add wave -noupdate /lcd_top_tb/DUV/CTRL/LS_Busy
add wave -noupdate /lcd_top_tb/DUV/CTRL/ML_Busy
add wave -noupdate /lcd_top_tb/DUV/CTRL/FIFO_Rd
add wave -noupdate /lcd_top_tb/DUV/CTRL/FIFO_RdData
add wave -noupdate /lcd_top_tb/DUV/CTRL/FIFO_Empty
add wave -noupdate /lcd_top_tb/DUV/CTRL/curr_word_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/curr_word_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/state_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/state_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/phase_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/phase_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/dcn_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/dcn_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/wrn_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/wrn_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/rdn_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/rdn_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/csn_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/csn_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/fiford_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/fiford_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/d_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/d_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/lsrddata_reg
add wave -noupdate /lcd_top_tb/DUV/CTRL/lsrddata_next
add wave -noupdate /lcd_top_tb/DUV/CTRL/flipper
add wave -noupdate /lcd_top_tb/DUV/CTRL/NEW_FRAME_CMD
add wave -noupdate /lcd_top_tb/DUV/SLAV/clk
add wave -noupdate /lcd_top_tb/DUV/SLAV/rst_n
add wave -noupdate /lcd_top_tb/DUV/SLAV/AS_Address
add wave -noupdate /lcd_top_tb/DUV/SLAV/AS_ChipSelect
add wave -noupdate /lcd_top_tb/DUV/SLAV/AS_Wr
add wave -noupdate /lcd_top_tb/DUV/SLAV/AS_WrData
add wave -noupdate /lcd_top_tb/DUV/SLAV/AS_Rd
add wave -noupdate /lcd_top_tb/DUV/SLAV/AS_RdData
add wave -noupdate /lcd_top_tb/DUV/SLAV/AS_IRQ
add wave -noupdate /lcd_top_tb/DUV/SLAV/AS_WaitRequest
add wave -noupdate /lcd_top_tb/DUV/SLAV/LS_Busy
add wave -noupdate /lcd_top_tb/DUV/SLAV/LS_DC_n
add wave -noupdate /lcd_top_tb/DUV/SLAV/LS_Wr_n
add wave -noupdate /lcd_top_tb/DUV/SLAV/LS_Rd_n
add wave -noupdate /lcd_top_tb/DUV/SLAV/LS_WrData
add wave -noupdate /lcd_top_tb/DUV/SLAV/LS_RdData
add wave -noupdate /lcd_top_tb/DUV/SLAV/MS_Address
add wave -noupdate /lcd_top_tb/DUV/SLAV/MS_Length
add wave -noupdate /lcd_top_tb/DUV/SLAV/MS_StartDMA
add wave -noupdate /lcd_top_tb/DUV/SLAV/state_reg
add wave -noupdate /lcd_top_tb/DUV/SLAV/state_next
add wave -noupdate /lcd_top_tb/DUV/SLAV/waitbusy_reg
add wave -noupdate /lcd_top_tb/DUV/SLAV/waitbusy_next
add wave -noupdate /lcd_top_tb/DUV/SLAV/addr_reg
add wave -noupdate /lcd_top_tb/DUV/SLAV/addr_next
add wave -noupdate /lcd_top_tb/DUV/SLAV/len_reg
add wave -noupdate /lcd_top_tb/DUV/SLAV/len_next
add wave -noupdate /lcd_top_tb/DUV/SLAV/dma_state_reg
add wave -noupdate /lcd_top_tb/DUV/SLAV/dma_state_next
add wave -noupdate /lcd_top_tb/DUV/SLAV/dma_waitbusy_reg
add wave -noupdate /lcd_top_tb/DUV/SLAV/dma_waitbusy_next
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {190 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
