# TCL File Generated by Component Editor 16.0
# Fri Dec 09 10:47:41 CET 2016
# DO NOT MODIFY


# 
# lt24 "LT24 controller" v1.0
# Thomas Verelst and Lukas Moser 2016.12.09.10:47:41
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module lt24
# 
set_module_property DESCRIPTION ""
set_module_property NAME lt24
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Thomas Verelst and Lukas Moser"
set_module_property DISPLAY_NAME "LT24 controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file lcd_controller.vhd VHDL PATH ../hdl/lcd_controller.vhd
add_fileset_file lcd_master.vhd VHDL PATH ../hdl/lcd_master.vhd
add_fileset_file lcd_slave.vhd VHDL PATH ../hdl/lcd_slave.vhd
add_fileset_file lcd_fifo.vhd VHDL PATH ../hdl/lcd_fifo.vhd
add_fileset_file lcd_top.vhd VHDL PATH ../hdl/lcd_top.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 AS_Wr write Input 1
add_interface_port avalon_slave_0 AS_WrData writedata Input 32
add_interface_port avalon_slave_0 AS_Rd read Input 1
add_interface_port avalon_slave_0 AS_RdData readdata Output 32
add_interface_port avalon_slave_0 AS_WaitRequest waitrequest Output 1
add_interface_port avalon_slave_0 AS_Address address Input 2
add_interface_port avalon_slave_0 AS_ChipSelect chipselect Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master AM_Address address Output 32
add_interface_port avalon_master AM_BurstCount burstcount Output 8
add_interface_port avalon_master AM_ByteEnable byteenable Output 4
add_interface_port avalon_master AM_Rd read Output 1
add_interface_port avalon_master AM_RdData readdata Input 32
add_interface_port avalon_master AM_RdDataValid readdatavalid Input 1
add_interface_port avalon_master AM_WaitRequest waitrequest Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender AS_IRQ irq Output 1


# 
# connection point conduit_D
# 
add_interface conduit_D conduit end
set_interface_property conduit_D associatedClock clock
set_interface_property conduit_D associatedReset reset_sink
set_interface_property conduit_D ENABLED true
set_interface_property conduit_D EXPORT_OF ""
set_interface_property conduit_D PORT_NAME_MAP ""
set_interface_property conduit_D CMSIS_SVD_VARIABLES ""
set_interface_property conduit_D SVD_ADDRESS_GROUP ""

add_interface_port conduit_D D stdlogic_vector Output 16


# 
# connection point conduit_DC_n
# 
add_interface conduit_DC_n conduit end
set_interface_property conduit_DC_n associatedClock clock
set_interface_property conduit_DC_n associatedReset reset_sink
set_interface_property conduit_DC_n ENABLED true
set_interface_property conduit_DC_n EXPORT_OF ""
set_interface_property conduit_DC_n PORT_NAME_MAP ""
set_interface_property conduit_DC_n CMSIS_SVD_VARIABLES ""
set_interface_property conduit_DC_n SVD_ADDRESS_GROUP ""

add_interface_port conduit_DC_n DC_n stdlogic Output 1


# 
# connection point conduit_Rd_n
# 
add_interface conduit_Rd_n conduit end
set_interface_property conduit_Rd_n associatedClock clock
set_interface_property conduit_Rd_n associatedReset reset_sink
set_interface_property conduit_Rd_n ENABLED true
set_interface_property conduit_Rd_n EXPORT_OF ""
set_interface_property conduit_Rd_n PORT_NAME_MAP ""
set_interface_property conduit_Rd_n CMSIS_SVD_VARIABLES ""
set_interface_property conduit_Rd_n SVD_ADDRESS_GROUP ""

add_interface_port conduit_Rd_n Rd_n stdlogic Output 1


# 
# connection point conduit_Wr_n
# 
add_interface conduit_Wr_n conduit end
set_interface_property conduit_Wr_n associatedClock clock
set_interface_property conduit_Wr_n associatedReset reset_sink
set_interface_property conduit_Wr_n ENABLED true
set_interface_property conduit_Wr_n EXPORT_OF ""
set_interface_property conduit_Wr_n PORT_NAME_MAP ""
set_interface_property conduit_Wr_n CMSIS_SVD_VARIABLES ""
set_interface_property conduit_Wr_n SVD_ADDRESS_GROUP ""

add_interface_port conduit_Wr_n Wr_n stdlogic Output 1


# 
# connection point conduit_CS_n
# 
add_interface conduit_CS_n conduit end
set_interface_property conduit_CS_n associatedClock clock
set_interface_property conduit_CS_n associatedReset reset_sink
set_interface_property conduit_CS_n ENABLED true
set_interface_property conduit_CS_n EXPORT_OF ""
set_interface_property conduit_CS_n PORT_NAME_MAP ""
set_interface_property conduit_CS_n CMSIS_SVD_VARIABLES ""
set_interface_property conduit_CS_n SVD_ADDRESS_GROUP ""

add_interface_port conduit_CS_n CS_n stdlogic Output 1


# 
# connection point conduit_LCD_ON
# 
add_interface conduit_LCD_ON conduit end
set_interface_property conduit_LCD_ON associatedClock clock
set_interface_property conduit_LCD_ON associatedReset ""
set_interface_property conduit_LCD_ON ENABLED true
set_interface_property conduit_LCD_ON EXPORT_OF ""
set_interface_property conduit_LCD_ON PORT_NAME_MAP ""
set_interface_property conduit_LCD_ON CMSIS_SVD_VARIABLES ""
set_interface_property conduit_LCD_ON SVD_ADDRESS_GROUP ""

add_interface_port conduit_LCD_ON LCD_ON stdlogic Output 1


# 
# connection point conduit_Reset
# 
add_interface conduit_Reset conduit end
set_interface_property conduit_Reset associatedClock clock
set_interface_property conduit_Reset associatedReset reset_sink
set_interface_property conduit_Reset ENABLED true
set_interface_property conduit_Reset EXPORT_OF ""
set_interface_property conduit_Reset PORT_NAME_MAP ""
set_interface_property conduit_Reset CMSIS_SVD_VARIABLES ""
set_interface_property conduit_Reset SVD_ADDRESS_GROUP ""

add_interface_port conduit_Reset Reset_n stdlogic Output 1

